plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	testImplementation "org.junit.jupiter:junit-jupiter-api:5.11.4"
	testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.11.4"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.11.4"
}

sourceSets {
	stubs {
		compileClasspath += sourceSets.main.compileClasspath
	}
	main {
		compileClasspath += sourceSets.stubs.output
	}
}

compileJava.dependsOn compileStubsJava

tasks.named('jar') {
	manifest {
		attributes(
			'Premain-Class': 'me.fy2ne.muto.engine.MutoAgent',
			'Agent-Class': 'me.fy2ne.muto.engine.MutoAgent',
			'Can-Retransform-Classes': 'true',
			'Can-Redefine-Classes': 'true'
		)
	}
}

test {
	useJUnitPlatform()
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
